Ninja: DiskInterfaceTest Class Reference
DiskInterfaceTest Class Reference
Public Member Functions
string GetSystemTempDir ()
string MakeTempDir ()
virtual void SetUp ()
virtual void TearDown ()
Public Attributes
RealDiskInterface disk_
string start_dir_
string temp_dir_name_
Detailed Description
Definition at line 243 of file ninja_test.cc.
Member Function Documentation
string DiskInterfaceTest::GetSystemTempDir () [inline]
Definition at line 269 of file ninja_test.cc.
Referenced by SetUp().
string DiskInterfaceTest::MakeTempDir () [inline]
Definition at line 283 of file ninja_test.cc.
Referenced by SetUp().
virtual void DiskInterfaceTest::SetUp () [inline, virtual]
Definition at line 245 of file ninja_test.cc.
References GetSystemTempDir(), MakeTempDir(), start_dir_, and temp_dir_name_.
virtual void DiskInterfaceTest::TearDown () [inline, virtual]
Definition at line 259 of file ninja_test.cc.
References start_dir_, and temp_dir_name_.
Member Data Documentation
RealDiskInterface DiskInterfaceTest::disk_
Definition at line 291 of file ninja_test.cc.
string DiskInterfaceTest::start_dir_
Definition at line 289 of file ninja_test.cc.
Referenced by SetUp(), and TearDown().
string DiskInterfaceTest::temp_dir_name_
Definition at line 290 of file ninja_test.cc.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
ninja_test.cc