Ninja: ninja_test.cc File Reference
ninja_test.cc File Reference
#include <gtest/gtest.h>
#include "build.h"
#include "graph.h"
#include "parsers.h"
#include "test.h"
Classes
class DiskInterfaceTest
struct StatTest
struct TestEnv
Functions
TEST (State, Basic)
TEST (EvalString, PlainText)
TEST (EvalString, OneVariableUpperCase)
TEST (EvalString, Dollars)
TEST (EvalString, Error)
TEST (EvalString, OneVariable)
TEST (EvalString, CurlyError)
TEST (EvalString, Curlies)
TEST_F (StatTest, Simple)
TEST_F (DiskInterfaceTest, RemoveFile)
TEST_F (StatTest, Tree)
TEST_F (StatTest, Middle)
TEST_F (DiskInterfaceTest, ReadFile)
TEST_F (DiskInterfaceTest, MakeDirs)
TEST_F (StatTest, TwoStep)
TEST_F (DiskInterfaceTest, Stat)
Function Documentation
TEST (State , Basic)
Definition at line 27 of file ninja_test.cc.
References State::AddEdge(), State::AddIn(), State::AddOut(), State::AddRule(), Node::dirty(), Edge::EvaluateCommand(), State::GetNode(), and Rule::ParseCommand().
TEST (EvalString , PlainText)
Definition at line 52 of file ninja_test.cc.
References EvalString::Evaluate(), and EvalString::Parse().
TEST (EvalString , OneVariableUpperCase)
Definition at line 70 of file ninja_test.cc.
References EvalString::Evaluate(), EvalString::Parse(), EvalString::unparsed(), and TestEnv::vars.
TEST (EvalString , Dollars)
Definition at line 107 of file ninja_test.cc.
References EvalString::Evaluate(), EvalString::Parse(), and TestEnv::vars.
TEST (EvalString , Error)
Definition at line 81 of file ninja_test.cc.
References EvalString::Parse().
TEST (EvalString , OneVariable)
Definition at line 59 of file ninja_test.cc.
References EvalString::Evaluate(), EvalString::Parse(), EvalString::unparsed(), and TestEnv::vars.
TEST (EvalString , CurlyError)
Definition at line 89 of file ninja_test.cc.
References EvalString::Parse().
TEST (EvalString , Curlies)
Definition at line 97 of file ninja_test.cc.
References EvalString::Evaluate(), EvalString::Parse(), and TestEnv::vars.
TEST_F (StatTest , Simple)
Definition at line 146 of file ninja_test.cc.
References AssertParse(), Node::file_, Node::in_edge_, Edge::RecomputeDirty(), and FileStat::Stat().
TEST_F (DiskInterfaceTest , RemoveFile)
Definition at line 332 of file ninja_test.cc.
TEST_F (StatTest , Tree)
Definition at line 178 of file ninja_test.cc.
References AssertParse(), Node::file_, Node::in_edge_, Edge::RecomputeDirty(), and FileStat::Stat().
TEST_F (StatTest , Middle)
Definition at line 195 of file ninja_test.cc.
References AssertParse(), Node::file_, Node::in_edge_, Edge::RecomputeDirty(), and FileStat::Stat().
TEST_F (DiskInterfaceTest , ReadFile)
Definition at line 312 of file ninja_test.cc.
TEST_F (DiskInterfaceTest , MakeDirs)
Definition at line 328 of file ninja_test.cc.
TEST_F (StatTest , TwoStep)
Definition at line 160 of file ninja_test.cc.
References AssertParse(), Node::file_, Node::in_edge_, Edge::RecomputeDirty(), and FileStat::Stat().
TEST_F (DiskInterfaceTest , Stat)
Definition at line 294 of file ninja_test.cc.