Ninja: BuildStatus Struct Reference
BuildStatus Struct Reference
Tracks the status of a build: completion fraction, printing updates.
Public Member Functions
void BuildEdgeFinished (Edge *edge, bool success, const string &output, int *start_time, int *end_time)
void BuildEdgeStarted (Edge *edge)
home evanm projects ninja src
build cc home evanm projects
ninja src build cc home evanm
projects ninja src build cc
home evanm projects ninja src
build cc home evanm projects
ninja src build cc home evanm
projects ninja src build cc
home evanm projects ninja src
build cc BuildStatus (const BuildConfig &config)
void PlanHasTotalEdges (int total)
Private Types
typedef map< Edge *, int > RunningEdgeMap
Map of running edge to time the edge started running.
Private Member Functions
void PrintStatus (Edge *edge)
Private Attributes
const BuildConfig & config_
int finished_edges_
int64_t last_update_millis_
Time we last printed an update.
RunningEdgeMap running_edges_
bool smart_terminal_
Whether we can do fancy terminal control codes.
int64_t start_time_millis_
Time the build started.
int started_edges_
int total_edges_
Detailed Description
Tracks the status of a build: completion fraction, printing updates.
Definition at line 36 of file build.cc.
Member Typedef Documentation
typedef map<Edge*, int> BuildStatus::RunningEdgeMap [private]
Map of running edge to time the edge started running.
Definition at line 63 of file build.cc.
Constructor & Destructor Documentation
BuildStatus::BuildStatus (const BuildConfig & config)
Definition at line 63 of file build.cc.
Member Function Documentation
void BuildStatus::BuildEdgeFinished (Edge * edge, bool success, const string & output, int * start_time, int * end_time)
Definition at line 92 of file build.cc.
References config_, Edge::EvaluateCommand(), finished_edges_, GetTimeMillis(), last_update_millis_, PrintStatus(), BuildConfig::QUIET, running_edges_, smart_terminal_, start_time_millis_, total_edges_, and BuildConfig::verbosity.
Referenced by Builder::FinishEdge().
void BuildStatus::BuildEdgeStarted (Edge * edge)
Definition at line 84 of file build.cc.
References GetTimeMillis(), PrintStatus(), running_edges_, start_time_millis_, and started_edges_.
Referenced by Builder::StartEdge().
void BuildStatus::PlanHasTotalEdges (int total)
Definition at line 80 of file build.cc.
References total_edges_.
Referenced by Builder::Build().
void BuildStatus::PrintStatus (Edge * edge) [private]
Definition at line 136 of file build.cc.
References config_, Edge::EvaluateCommand(), Edge::GetDescription(), BuildConfig::QUIET, smart_terminal_, started_edges_, total_edges_, BuildConfig::VERBOSE, and BuildConfig::verbosity.
Referenced by BuildEdgeFinished(), and BuildEdgeStarted().
Member Data Documentation
const BuildConfig& BuildStatus::config_ [private]
Definition at line 53 of file build.cc.
Referenced by BuildEdgeFinished(), and PrintStatus().
int BuildStatus::finished_edges_ [private]
Definition at line 60 of file build.cc.
Referenced by BuildEdgeFinished().
int64_t BuildStatus::last_update_millis_ [private]
Time we last printed an update.
Definition at line 58 of file build.cc.
Referenced by BuildEdgeFinished().
RunningEdgeMap BuildStatus::running_edges_ [private]
Definition at line 64 of file build.cc.
Referenced by BuildEdgeFinished(), and BuildEdgeStarted().
bool BuildStatus::smart_terminal_ [private]
Whether we can do fancy terminal control codes.
Definition at line 67 of file build.cc.
Referenced by BuildEdgeFinished(), and PrintStatus().
int64_t BuildStatus::start_time_millis_ [private]
Time the build started.
Definition at line 56 of file build.cc.
Referenced by BuildEdgeFinished(), and BuildEdgeStarted().
int BuildStatus::started_edges_ [private]
Definition at line 60 of file build.cc.
Referenced by BuildEdgeStarted(), and PrintStatus().
int BuildStatus::total_edges_ [private]
Definition at line 60 of file build.cc.
Referenced by BuildEdgeFinished(), PlanHasTotalEdges(), and PrintStatus().
The documentation for this struct was generated from the following file:
build.cc