Ninja: StatTest Struct Reference
StatTest Struct Reference
Public Member Functions
Node * GetNode (const string &path)
virtual bool MakeDir (const string &path)
virtual bool MakeDir (const std::string &path)=0
Create a directory, returning false on failure.
bool MakeDirs (const std::string &path)
Create all the parent directories for path; like mkdir -p `basename path`.
virtual std::string ReadFile (const std::string &path, std::string *err)=0
Read a file to a string. Fill in |err| on error.
virtual string ReadFile (const string &path, string *err)
virtual int RemoveFile (const string &path)
virtual int RemoveFile (const std::string &path)=0
Remove the file named path.
virtual int Stat (const std::string &path)=0
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
virtual int Stat (const string &path)
Public Attributes
map< string, time_t > mtimes_
State state_
vector< string > stats_
Detailed Description
Definition at line 117 of file ninja_test.cc.
Member Function Documentation
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Definition at line 25 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty().
virtual bool StatTest::MakeDir (const string & path) [inline, virtual]
Definition at line 121 of file ninja_test.cc.
virtual bool DiskInterface::MakeDir (const std::string & path) [pure virtual, inherited]
Create a directory, returning false on failure.
Implemented in RealDiskInterface.
Referenced by DiskInterface::MakeDirs().
bool DiskInterface::MakeDirs (const std::string & path) [inherited]
Create all the parent directories for path; like mkdir -p `basename path`.
Definition at line 45 of file disk_interface.cc.
References DiskInterface::MakeDir(), and DiskInterface::Stat().
Referenced by Builder::StartEdge().
virtual std::string DiskInterface::ReadFile (const std::string & path, std::string * err) [pure virtual, inherited]
Read a file to a string. Fill in |err| on error.
Implemented in RealDiskInterface.
Referenced by Edge::LoadDepFile().
virtual string StatTest::ReadFile (const string & path, string * err) [inline, virtual]
Definition at line 125 of file ninja_test.cc.
virtual int StatTest::RemoveFile (const string & path) [inline, virtual]
Definition at line 129 of file ninja_test.cc.
virtual int DiskInterface::RemoveFile (const std::string & path) [pure virtual, inherited]
Remove the file named path.
It behaves like 'rm -f path' so no errors are reported if it does not exists.
Returns:
0 if the file has been removed, 1 if the file does not exist, and -1 if an error occurs.
Implemented in RealDiskInterface.
Referenced by Cleaner::RemoveFile().
virtual int DiskInterface::Stat (const std::string & path) [pure virtual, inherited]
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
Implemented in RealDiskInterface.
Referenced by Cleaner::FileExists(), DiskInterface::MakeDirs(), and FileStat::Stat().
int StatTest::Stat (const string & path) [virtual]
Definition at line 138 of file ninja_test.cc.
References mtimes_, and stats_.
Member Data Documentation
map<string, time_t> StatTest::mtimes_
Definition at line 134 of file ninja_test.cc.
Referenced by Stat().
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 33 of file test.h.
Referenced by BuildTest::BuildTest(), StateTestWithBuiltinRules::GetNode(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
vector<string> StatTest::stats_
Definition at line 135 of file ninja_test.cc.
Referenced by Stat().
The documentation for this struct was generated from the following file:
ninja_test.cc