Ninja: CommandRunner Struct Reference
CommandRunner Struct Reference
CommandRunner is an interface that wraps running the build subcommands.
#include <build.h>
Public Member Functions
virtual bool CanRunMore ()=0
virtual bool StartCommand (Edge *edge)=0
virtual Edge * WaitForCommand (bool *success, string *output)=0
Wait for a command to complete.
virtual ~CommandRunner ()
Detailed Description
CommandRunner is an interface that wraps running the build subcommands.
This allows tests to abstract out running commands. RealCommandRunner is an implementation that actually runs commands.
Definition at line 71 of file build.h.
Constructor & Destructor Documentation
virtual CommandRunner::~CommandRunner () [inline, virtual]
Definition at line 72 of file build.h.
Member Function Documentation
virtual bool CommandRunner::CanRunMore () [pure virtual]
Implemented in RealCommandRunner, DryRunCommandRunner, and BuildTest.
Referenced by Builder::Build().
virtual bool CommandRunner::StartCommand (Edge * edge) [pure virtual]
Implemented in RealCommandRunner, DryRunCommandRunner, and BuildTest.
Referenced by Builder::StartEdge().
virtual Edge* CommandRunner::WaitForCommand (bool * success, string * output) [pure virtual]
Wait for a command to complete.
Implemented in RealCommandRunner, DryRunCommandRunner, and BuildTest.
Referenced by Builder::Build().
The documentation for this struct was generated from the following file:
build.h